project:
  type: website
  output-dir: docs

website:
  title: "qtm350-quiz02"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Life Expectancy and GDP"
        href: life-gdp.qmd
      - text: "Life Expectancy and Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



